import Head from "next/head";
import styles from "../styles/app.module.scss";

import Intro from "../sections/Intro";
import CSSSection from "../sections/CSSSection";
import Scalable from "../sections/Scalable";
import JSSection from "../sections/JSSection";
import ButtonsSection from "../sections/ButtonsSection";
import BenefitsSection from "../sections/BenefitsSection";
import CanIUse from "../sections/CanIUse";
import HowItWorksSection from "../sections/HowItWorksSection";
import CompareSection from "../sections/CompareSection";
import Footer from "../sections/Footer";

(async function () {
  if (!("paintWorklet" in CSS)) {
    await import("css-paint-polyfill");
  }

  CSS.paintWorklet.addModule(
    `${process.env.PUBLIC_URL}/paintWorklet/squircle.js`
  );
})();

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.app}>
        <Intro />
        <CSSSection />
        <Scalable />
        <HowItWorksSection />
        <JSSection />
        <ButtonsSection />
        <BenefitsSection />
        <CanIUse />
        <CompareSection />
        <Footer />
      </main>
    </>
  );
}
